{
 "title": "FOREX",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "content": "\n# **US Dollar** to **Euro** \nForeign Exchange Data presented LIVE\\\nfor your convenience and enjoyment!\n\n\n\n"
  },
  {
   "title": "Change in Exchange Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Last Refreshed", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Exchange Rate",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "Last Refreshed"
    }
   ]
  },
  {
   "title": "High",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "Last Refreshed", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Exchange Rate",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "Last Refreshed"
    }
   ]
  },
  {
   "title": "Low",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "Last Refreshed", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Exchange Rate",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "Last Refreshed"
    }
   ]
  },
  { "title": "Live Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Exchange Rate - A dollar is worth:",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "Last Refreshed", "id": "2", "settings": { "interval": "200s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Exchange Rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "Last Refreshed"
    }
   ]
  },
  {
   "title": "Bid / Ask Price Spread",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "Last Refreshed", "id": "2", "settings": { "interval": "200s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Ask Price",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "Last Refreshed"
    },
    {
     "bucketAggs": [
      { "field": "Last Refreshed", "id": "2", "settings": { "interval": "200s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Bid Price",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "Last Refreshed"
    }
   ]
  }
 ]
}